spring:
  datasource:
    url: jdbc:postgresql://localhost:5452/order
    username: nathan
    password: nathan
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
      name: order-service
  server:
    port: 8050

